"""
Part 10 -- Open a real model and recognise everything inside it.

  pip install transformers          # plus torch, which you already have
  python inspect_hf_model.py        # downloads GPT-2 small once (~550 MB)

You built a GPT in phase3-transformers/tiny_gpt.py. This file loads the real
GPT-2 small from the Hugging Face Hub and shows that it is THE SAME MACHINE:

  1. config.json next to your Config, field by field
  2. every tensor in the checkpoint, with its shape and the lesson that built it
     (including the one trap: GPT-2 stores its linear weights TRANSPOSED
     relative to nn.Linear)
  3. the parameter count, recomputed from the config alone with the course's
     formula, and asserted equal to the real count: 124,439,808
  4. one forward pass BY HAND, using nothing but the raw tensors and the maths
     from your lessons, asserted equal to model(...).logits
  5. text generated by YOUR sampling loop (temperature + top-k) on top of the
     real model's logits, which is all that model.generate() is

No API key. Nothing is trained. If `transformers` is missing or the model
cannot be downloaded, the script explains what to do and exits cleanly.
"""
import argparse
import math
import sys

import torch
import torch.nn.functional as F

MODEL_ID = "gpt2"   # GPT-2 small; on the Hub its full name is openai-community/gpt2


# ----------------------------------------------------------------------
# 0. Pure helpers. No download needed: tests/test_engineering_bridge.py
#    imports these directly.
# ----------------------------------------------------------------------
def gpt2_param_count(vocab_size, n_positions, n_embd, n_layer, tied=True):
    """The counting rules from the Build GPT lesson (course/src/lib/params.ts).

    n_head is NOT an argument: heads split D, they do not add to it.
    """
    D = n_embd
    tok_emb = vocab_size * D                 # wte
    pos_emb = n_positions * D                # wpe
    attn = 4 * D * D + 4 * D                 # c_attn (3D*D + 3D) + c_proj (D*D + D)
    mlp = 8 * D * D + 5 * D                  # c_fc (4D*D + 4D) + c_proj (4D*D + D)
    norms = 4 * D                            # ln_1 and ln_2: gain + bias each
    final_norm = 2 * D                       # ln_f
    head = 0 if tied else vocab_size * D     # lm_head shares storage with wte
    return tok_emb + pos_emb + n_layer * (attn + mlp + norms) + final_norm + head


def gelu_new(x):
    """GPT-2's activation ("gelu_new" in its config.json): the tanh approximation
    of GELU from the original GPT code. nn.GELU() in tiny_gpt.py is the exact
    version; the two differ by less than 0.001 everywhere, but to reproduce
    GPT-2's logits to many decimals we must use the one it was trained with."""
    return 0.5 * x * (1.0 + torch.tanh(math.sqrt(2.0 / math.pi) * (x + 0.044715 * x.pow(3))))


def layer_norm(x, weight, bias, eps):
    """LayerNorm by hand (Transformer block lesson): per token, subtract the mean,
    divide by the standard deviation, then a learned gain and bias."""
    mean = x.mean(dim=-1, keepdim=True)
    var = ((x - mean) ** 2).mean(dim=-1, keepdim=True)
    return (x - mean) / torch.sqrt(var + eps) * weight + bias


def manual_forward(sd, ids, n_layer, n_head, eps=1e-5):
    """GPT-2's forward pass using ONLY the raw tensors in the state dict `sd`.

    ids: LongTensor (T,). Returns logits (T, V).
    Every line is a line you have already written in tiny_gpt.py. The one
    difference is the orientation of the weights: GPT-2's Conv1D stores
    weight as (in, out), so the layer is  x @ W + b  with NO transpose.
    (nn.Linear stores (out, in) and computes x @ W.T + b.)
    """
    T = ids.shape[0]
    wte, wpe = sd["transformer.wte.weight"], sd["transformer.wpe.weight"]
    x = wte[ids] + wpe[torch.arange(T)]                        # (T, D) meaning + position
    D = x.shape[1]
    hd = D // n_head
    causal = torch.tril(torch.ones(T, T, dtype=torch.bool))    # the causal mask

    for i in range(n_layer):
        p = f"transformer.h.{i}."
        # ---- communicate: x = x + attn(ln_1(x)) ----
        h = layer_norm(x, sd[p + "ln_1.weight"], sd[p + "ln_1.bias"], eps)
        qkv = h @ sd[p + "attn.c_attn.weight"] + sd[p + "attn.c_attn.bias"]   # (T, 3D) fused
        q, k, v = qkv.split(D, dim=-1)                                       # each (T, D)
        q = q.view(T, n_head, hd).transpose(0, 1)                            # (H, T, hd)
        k = k.view(T, n_head, hd).transpose(0, 1)
        v = v.view(T, n_head, hd).transpose(0, 1)
        att = q @ k.transpose(-2, -1) / math.sqrt(hd)                        # (H, T, T)
        att = att.masked_fill(~causal, float("-inf"))
        att = F.softmax(att, dim=-1)
        y = (att @ v).transpose(0, 1).reshape(T, D)                          # concat heads
        x = x + y @ sd[p + "attn.c_proj.weight"] + sd[p + "attn.c_proj.bias"]
        # ---- compute: x = x + mlp(ln_2(x)) ----
        h = layer_norm(x, sd[p + "ln_2.weight"], sd[p + "ln_2.bias"], eps)
        h = gelu_new(h @ sd[p + "mlp.c_fc.weight"] + sd[p + "mlp.c_fc.bias"])  # (T, 4D)
        x = x + h @ sd[p + "mlp.c_proj.weight"] + sd[p + "mlp.c_proj.bias"]

    x = layer_norm(x, sd["transformer.ln_f.weight"], sd["transformer.ln_f.bias"], eps)
    return x @ wte.T                                           # tied head: (T, D) @ (D, V)


def sample_next(logits, temperature=1.0, top_k=None, generator=None):
    """Your sampling step from the Inference lesson: temperature, optional top-k,
    softmax, then one weighted draw. logits: (V,). Returns a Python int."""
    logits = logits / temperature
    if top_k is not None:
        kth = torch.topk(logits, top_k).values[-1]             # the k-th largest score
        logits = logits.masked_fill(logits < kth, float("-inf"))
    probs = F.softmax(logits, dim=-1)
    return int(torch.multinomial(probs, num_samples=1, generator=generator))


# which lesson built each kind of tensor; first matching key wins
LESSON_OF = [
    ("wte", "token embedding table  = tok_emb     (Embeddings, Build GPT)"),
    ("wpe", "position table         = pos_emb     (Transformer block: learned positions)"),
    ("ln_1", "LayerNorm before attn  = Block.ln1   (Transformer block: pre-norm)"),
    ("attn.c_attn", "fused Wq, Wk, Wv       = attn.qkv    (Attention; fused in Build GPT)"),
    ("attn.c_proj", "output projection Wo   = attn.proj   (Causal masks and multiple heads)"),
    ("ln_2", "LayerNorm before MLP   = Block.ln2   (Transformer block)"),
    ("mlp.c_fc", "MLP up, D -> 4D        = ffn.net[0]  (Neurons and layers, Transformer block)"),
    ("mlp.c_proj", "MLP down, 4D -> D      = ffn.net[2]  (Transformer block)"),
    ("ln_f", "final LayerNorm        = GPT.ln_f    (Build GPT)"),
    ("lm_head", "the head, tied to wte  = GPT.head    (Build GPT: weight tying)"),
]


def lesson_for(name):
    for key, lesson in LESSON_OF:
        if key in name:
            return lesson
    return "?"


def banner(title):
    print("\n" + "=" * 74)
    print(title)
    print("=" * 74)


# ----------------------------------------------------------------------
# Loading, with a graceful exit
# ----------------------------------------------------------------------
def load():
    try:
        from transformers import AutoModelForCausalLM, AutoTokenizer
    except ImportError:
        print("This script needs the Hugging Face `transformers` library.\n"
              "  pip install transformers\n"
              "Then run it again:  python phase6-engineering/inspect_hf_model.py")
        sys.exit(0)
    try:
        tok = AutoTokenizer.from_pretrained(MODEL_ID)
        model = AutoModelForCausalLM.from_pretrained(MODEL_ID)   # GPT-2 was saved in fp32, and loads as fp32
    except Exception as e:   # no network, proxy, disk full...
        print(f"Could not download or load '{MODEL_ID}': {type(e).__name__}: {e}\n\n"
              "The first run needs internet access to huggingface.co (about 550 MB,\n"
              "cached afterwards in ~/.cache/huggingface). Run it again when online.")
        sys.exit(0)
    model.eval()   # dropout off: the same switch as model.eval() in tiny_gpt.py
    return tok, model


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--prompt", default="The cat sat on the")
    ap.add_argument("--tokens", type=int, default=25)
    args = ap.parse_args()

    tok, model = load()
    cfg = model.config

    # ------------------------------------------------------------------
    banner("1. config.json next to your Config")
    # ------------------------------------------------------------------
    rows = [
        ("n_layer", cfg.n_layer, "n_layer", 4, "how many Transformer blocks"),
        ("n_head", cfg.n_head, "n_head", 4, "attention heads per block"),
        ("n_embd", cfg.n_embd, "n_embd", 128, "D: numbers per token"),
        ("n_positions", cfg.n_positions, "context_len", 64, "rows in the position table"),
        ("vocab_size", cfg.vocab_size, "vocab_size", 65, "rows in the token table"),
    ]
    print(f"  {'GPT-2 config.json':<22}{'value':>8}    {'tiny_gpt.py Config':<20}{'value':>6}   meaning")
    for hf, hv, mine, mv, meaning in rows:
        print(f"  {hf:<22}{hv:>8}    {mine:<20}{mv:>6}   {meaning}")
    print(f"\n  head size = n_embd / n_head = {cfg.n_embd // cfg.n_head}"
          f"   activation = {cfg.activation_function}   layer_norm_epsilon = {cfg.layer_norm_epsilon}")
    print("  (tiny_gpt.py's vocab_size is set from the data: 65 characters of Shakespeare)")

    # ------------------------------------------------------------------
    banner("2. Every tensor, its shape, and the lesson that built it")
    # ------------------------------------------------------------------
    # named_parameters() yields each PARAMETER once. lm_head.weight is the same
    # object as wte.weight (weight tying), so it does not appear a second time.
    params = list(model.named_parameters())
    print("  outside the blocks:")
    for name, p in params:
        if ".h." not in name:
            print(f"    {name:<38}{str(tuple(p.shape)):<15}{lesson_for(name)}")
    print("\n  block 0 (blocks 1 to 11 have identical names and shapes):")
    for name, p in params:
        if ".h.0." in name:
            print(f"    {name:<38}{str(tuple(p.shape)):<15}{lesson_for(name)}")

    tied = model.lm_head.weight.data_ptr() == model.transformer.wte.weight.data_ptr()
    print(f"\n  lm_head.weight {tuple(model.lm_head.weight.shape)} shares memory with wte.weight: {tied}")

    # The trap. Your qkv is nn.Linear(D, 3D): weight shape (3D, D) = (out, in).
    # GPT-2 uses its own Conv1D layer: weight shape (D, 3D) = (in, out).
    c_attn = model.transformer.h[0].attn.c_attn
    print(f"\n  The one trap: c_attn is a {type(c_attn).__name__}, not an nn.Linear.")
    print(f"    c_attn.weight.shape           = {tuple(c_attn.weight.shape)}   (in, out)")
    print(f"    nn.Linear(768, 2304).weight   = {tuple(torch.nn.Linear(768, 2304).weight.shape)}   (out, in)")
    x = torch.randn(5, cfg.n_embd)
    same = torch.allclose(c_attn(x), x @ c_attn.weight + c_attn.bias, atol=1e-5)
    print(f"    c_attn(x) == x @ W + b  (no transpose): {same}")
    assert same
    print("    Same maths as your layer. Only the storage is transposed. Tools that treat")
    print("    every layer as nn.Linear (LoRA libraries, quantisers) must be told about this.")

    # ------------------------------------------------------------------
    banner("3. The parameter count, from the config alone")
    # ------------------------------------------------------------------
    real = sum(p.numel() for p in model.parameters())
    mine = gpt2_param_count(cfg.vocab_size, cfg.n_positions, cfg.n_embd, cfg.n_layer, tied=True)
    D, V, L = cfg.n_embd, cfg.vocab_size, cfg.n_layer
    print(f"  token table   V x D        = {V} x {D:<7}= {V * D:>12,}")
    print(f"  position tbl  ctx x D      = {cfg.n_positions} x {D:<8}= {cfg.n_positions * D:>12,}")
    print(f"  attention     L x (4D²+4D) = {L} x {4 * D * D + 4 * D:<10,}= {L * (4 * D * D + 4 * D):>12,}")
    print(f"  MLP           L x (8D²+5D) = {L} x {8 * D * D + 5 * D:<10,}= {L * (8 * D * D + 5 * D):>12,}")
    print(f"  LayerNorms    L x 4D + 2D                 = {L * 4 * D + 2 * D:>12,}")
    print(f"  head          tied to the token table     = {0:>12,}")
    print(f"  formula total                             = {mine:>12,}")
    print(f"  sum(p.numel() for p in model.parameters()) = {real:,}")
    assert mine == real == 124_439_808, (mine, real)
    print("  They match: 124,439,808. The '124M' in the model's name is this number.")
    # Why the Hub's file viewer says 137M: old GPT-2 checkpoints also saved each
    # block's causal mask (a 1024 x 1024 buffer of ones and zeros) as a tensor.
    print(f"  (The checkpoint FILE lists 137,022,720 numbers: the extra {L} x 1024 x 1024 ="
          f" {L * 1024 * 1024:,}\n   are the saved causal masks of old checkpoints. Masks are not parameters.)")

    # ------------------------------------------------------------------
    banner("4. One forward pass by hand, from the raw tensors")
    # ------------------------------------------------------------------
    ids = tok(args.prompt, return_tensors="pt").input_ids          # (1, T)
    print(f"  prompt    {args.prompt!r}")
    print(f"  tokens    {[tok.decode([i]) for i in ids[0].tolist()]}")
    print(f"  ids       {ids[0].tolist()}")
    sd = model.state_dict()
    with torch.no_grad():   # no recording for backprop: we are not training
        theirs = model(ids).logits[0]                              # (T, V)
        ours = manual_forward(sd, ids[0], cfg.n_layer, cfg.n_head, cfg.layer_norm_epsilon)
    diff = (theirs - ours).abs().max().item()
    print(f"  logits shape {tuple(ours.shape)}   largest |difference| over all {ours.numel():,} logits: {diff:.2e}")
    assert torch.allclose(theirs, ours, atol=1e-3, rtol=1e-4), diff
    print("  allclose: True. Your maths, their weights, the same numbers.")
    top = torch.topk(F.softmax(ours[-1], dim=-1), 5)
    print("  top 5 next tokens (from the hand-made logits):")
    for p, i in zip(top.values.tolist(), top.indices.tolist()):
        print(f"    {tok.decode([i])!r:<12}{p:6.1%}")

    # ------------------------------------------------------------------
    banner("5. Your generation loop on their logits")
    # ------------------------------------------------------------------
    # This loop IS model.generate(do_sample=True, temperature=0.8, top_k=40),
    # minus the KV cache (we re-run the whole sequence each step: fine for 25 tokens).
    g = torch.Generator().manual_seed(1337)
    out = ids.clone()
    with torch.no_grad():
        for _ in range(args.tokens):
            logits = model(out[:, -cfg.n_positions:]).logits[0, -1]   # last position only
            nxt = sample_next(logits, temperature=0.8, top_k=40, generator=g)
            out = torch.cat([out, torch.tensor([[nxt]])], dim=1)      # feed back in
    print(f"  temperature 0.8, top-k 40:\n    {tok.decode(out[0])!r}")

    greedy = model.generate(ids, max_new_tokens=args.tokens, do_sample=False,
                            pad_token_id=tok.eos_token_id)
    mine_greedy = ids.clone()
    with torch.no_grad():
        for _ in range(args.tokens):
            nxt = int(model(mine_greedy).logits[0, -1].argmax())
            mine_greedy = torch.cat([mine_greedy, torch.tensor([[nxt]])], dim=1)
    print(f"  greedy, model.generate():\n    {tok.decode(greedy[0])!r}")
    print(f"  greedy, your loop gives the identical ids: {torch.equal(greedy, mine_greedy)}")
    assert torch.equal(greedy, mine_greedy)
    print("\n  GPT-2 is a 2019 base model with no instruction tuning: expect fluent rambling,")
    print("  not answers. The point is that you now recognise every tensor that produced it.")


if __name__ == "__main__":
    main()
